markdown:    kramdown
highlighter: pygments
permalink:   pretty

# server
encoding:        UTF-8
port:            3333
title:           "ev-fdm"
github_username: "Evaneos"
baseurl: /ev-fdm
safe: true

collections:
  demos:
    output: true

exclude: [ node_module, README.md, bower.json, gulpfile.js, package.json, bower_component ]