markdown:    kramdown
highlighter: pygments
permalink:   pretty

# server
source:          docs
host:            0.0.0.0
port:            3333
baseurl:         /
url:             "http://evfdmdemo.dev.evaneos.com"
encoding:        UTF-8
title:           "EV-FDM Demo"
github_username: "Evaneos"

collections:
  demos:
    output: true
