markdown:    kramdown
highlighter: pygments
permalink:   pretty

# server
baseurl:         /
encoding:        UTF-8
port:            3333
title:           "ev-fdm"
github_username: "Evaneos"

safe: true

collections:
  demos:
    output: true
